version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 600
  method-complexity:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: 40
  identical-code:
    config:
      threshold: 40
exclude_patterns:
  - "Tests/"
  - "*.md"
  - "*.resolved"
