name: 'test'

on:
  push:

jobs:
  linux:
    container: 
      image: swift:5.2.3-bionic
    name: Running Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checking out repo'
      uses: actions/checkout@master
        
    - name: 'TestRail-Kit Tests'
      run: swift test --enable-test-discovery --sanitize=thread --enable-code-coverage       
    - name: Process coverage file
      run: llvm-cov export -format="lcov" .build/x86_64-unknown-linux-gnu/debug/testrail-kitPackageTests.xctest -ignore-filename-regex="(.build|TestUtils|Tests)" -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Pull curl
      run: apt-get update && apt-get install -y curl
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: info.lcov
        directory: Sources
